<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "materialize"
 *
 * Auto generated by Extension Builder 2016-04-30
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Materialize',
	'description' => '',
	'category' => 'distribution',
	'author' => 'Dimitri Pfaffenrodt',
	'author_email' => 'dimitri@pfaffenrodt.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.9.99',
			'fluid_styled_content' => '',
			'gridelements' => '',
			'vhs' => ''
		),
		'conflicts' => array(
			'styled_content' => ''
		),
		'suggests' => array(
		),
	),
);